### ISSUE TITLE
3d brain looks stretched out too wide

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_on-the-fly#36]
any idea why @ajdm

**Comment by ajdm** [comment]
I'm afraid not. As far as I can see, the dimensions of 800 px by 600 px are consistent throughout the HTML and WebGL, so I don't know why it's being stretched. Somewhat strangely, I don't seem to have any problems if I run the shiny app locally, and ``shinyRGL`` hasn't been updated for quite a while, so it shouldn't be due to a version difference.
