### ISSUE TITLE
neuron types (cross-linked to VFB) in results tables

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_on-the-fly#48]
* see PR #47

**Comment by dosumis** [comment]
To do this so that the results are consistent with what is displayed on VFB, assuming you already have VFB ids you can use the JSON files here:

https://github.com/VirtualFlyBrain/VFB_owl/tree/master/export

The README gives the JSON structure.  

This flycircuit neurons are here:

https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/master/export/flycircuit_plus.json

Use the VFBid of the neuron as the key (I'm assuming you already have this*), use the object_ids of Types with "isAnonymous": false

~~~~~.json
{
    "VFB_00000001": {
        "Types": [
            {
                "isAnonymous": false, 
                "objectId": "FBbt_00005106"
            }, 
~~~~~~

Link pattern: http://www.virtualflybrain.org/site/tools/anatomy_finder/index.htm?id=FBbt_00005106

* to find the UUID from the neuron table:

~~~~~~~~.sql
SELECT oi.shortFormID FROM owl_individual oi
JOIN neuron n on n.uuid=oi.uuid;
~~~~~~~~~
