### ISSUE TITLE
Allow NBLASTing against GAL4 driver lines of interest

### ISSUE THREAD

**Issue by josesho** [jefferislab/NBLAST_on-the-fly#71]
Currently the NBLAST desktop and the online 'on-the-fly' version only permit two options:

1. NBLAST against all ~16,000 Flycircuit neurons
2. NBLAST against a small subset of exemplar neurons that are representative of all ~16,000 FC neurons.

Will "better" results be obtained if one NBLASTs against a GAL4 driver line of interest? This will mean computing a similarity matrix for each driver line in the FC neuron list.

**Comment by jefferis** [comment]
Sent from my iPhone

> On 19 Aug 2015, at 23:05, Joses W. Ho <notifications@github.com> wrote:
> 
> Will "better" results be obtained if one NBLASTs against a GAL4 driver line of interest? This will mean computing a similarity matrix for each driver line in the FC neuron list.

Could you elaborate? Thanks, Greg.

**Comment by josesho** [comment]
Let's say I have a single neuron that I strongly believe to be Trh positive. NBLAST currently allows me to find neurons matching any of the ~16,000 FC neurons, which is no doubt useful. 

I just wonder if any sort of improved specificity might be attained if I just NBLASTed against just the Trh-Gal4 neurons? Another way to put it is, will "noise" be reduced? 

Of course, one could just run NBLAST and then filter for the neurons from a Gal4 line of interest. 

Just thinking aloud here - wanted to tag this as "suggestion" but couldn't seem to(?). Thanks!
Joses

**Comment by ajdm** [comment]
While NBLAST on-the-fly only allows comparing against all ~16,000 FlyCircuit neurons, or cluster exemplars, NBLAST desktop is much more flexible. Comparing just with Trh-Gal4 neurons from the full set (``dps``) can be done using:
```r
df <- attr(dps, 'df')
trh <- dps[df$Driver == "Trh-Gal4", ]
nblast(my_trf_neuron, trh)
```
which will be much faster than comparing against all neurons and then filtering the results afterwards.

**Comment by josesho** [comment]
Right -- but the similarity matrix used in that example will still be the
all-by-all (16,000 X 16,000) matrix.

There are ~2000 Trh-Gal4 neurons in the `dps` dataset, so would it be
profitable / appropriate to generate a seperate similarity matrix? Or would
that simply be a subset of the all-by-all matrix, so there's no point?

Thanks,
Joses

**Comment by jefferis** [comment]
> On 20 Aug 2015, at 05:46, James Manton <notifications@github.com> wrote:
> 
> df <- attr(dps, 'df') trh <- dps[df$Driver == "Trh-Gal4", ] nblast(my_trf_neuron, trh)

Or even

nblast(my_trf_neuron, subset(dps, Driver== "Trh-Gal4"))

The more general point is that although Trh Gal4 is a reasonsbly reliable marker most of the others are less so.

**Comment by ajdm** [comment]
> Right -- but the similarity matrix used in that example will still be the all-by-all (16,000 X 16,000) matrix.

Actually, in that example the scores are computed from scratch.

If you wanted to produce a sparse score matrix that had 16,000 × 16,000 elements, but only had values for the neurons you were interested in, the ``spare_score_mat`` function in [nat.nblast](https://github.com/jefferislab/nat.nblast/blob/master/R/scoremats.r#L203-L233) will allow you to do so.

**Comment by jefferis** [comment]
Just to add to @ajdm's last comment:

> If you wanted to produce a sparse score matrix that had 16,000 × 16,000 elements, but only had values for the neurons you were interested in, the spare_score_mat function in nat.nblast will allow you to do so.

The scorematrix used by flycircuit::fc_nblast is kept on disk since it is big ~ 2Gb with the bigmemory or ff packages providing relatively fast access to subsets of the matrix. If you are interested in doing clustering or searches using just 2000 neurons you can subset the original matrix to a make a standard in memory matrix which will be 1/64 of the original size – quite small enough to fit in main memory on any machine and with speed advantages to boot. Sparse matrices are more flexible in that a single matrix can include non square sets of neurons i.e. the equivalent of multiple all-by-all square matrices for different subsets of the starter neurons. 

If you think either of these approaches would be help, post a question to [nat-user](https://groups.google.com/forum/#!forum/nat-user) for more details. I am not sure that I see us adding this function to nblast on the fly at the moment.
