### ISSUE TITLE
scan() expected 'an integer', got '<?xml'

### ISSUE THREAD

**Issue by Alibohra** [jefferislab/NBLAST_on-the-fly#97]
Hi,
while uploading a tracing file with .scw I got an error saying **scan() expected 'an integer', got '<?xml'**. I am naive to the programming. no idea what to do

**Comment by jefferis** [comment]
Thanks for your interest. 

I think your file is not an swc file but some kind of xml format file. Perhaps it is a .traces file from the Fiji Simple Neurite Tracer?If so, then you should rename it so that it does not end in .swc because this is confusing the file identification routines. nat should be able to open a 

Otherwise you need to figure out how to really save as swc.

Best,

Greg.

**Comment by Alibohra** [comment]
Thanks Greg for super quick reply.
I renamed the file but I got this message **unable to obtain value for key 'adc8bce959cfc93cfe02380bc482b05d'**
Thank you for your help.
Best,
Ali

**Comment by jefferis** [comment]
Do you want to upload a copy of the file somewhere? Or send to me privately.

**Comment by Alibohra** [comment]
Hi Greg,
I have uploaded two file  (one .nrrd file and one .trace file) on dropbox.
here the link for the same:

https://www.dropbox.com/sh/f0ywk6ngeavdwsm/AACuDQKrH0hbPlZH8RdmsW00a?dl=0

Please let me know of further details required.

Thanks for your help.
Best,
Ali

**Comment by jefferis** [comment]
OK. So the reason that the .traces neuron won't open is because it actually contains 3 separate (unconnected) trees. My R packages load that in as 3 separate neurons (red, green, blue in image). If you want to search with this you will need to join the neurons together in Fiji. 
![image](https://user-images.githubusercontent.com/23763/32666293-dfb30246-c62e-11e7-89eb-f1511db04d48.png)

**Comment by jefferis** [comment]
See https://imagej.net/Simple_Neurite_Tracer#Tutorials

**Comment by Alibohra** [comment]
Thanks Greg.
That's really helpful. 
Regards, 
Ali
